# 使用语言
language: node_js
# node版本
node_js:
  - 10
# 设置只监听哪个分支
branches:
  only:
    - source
# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
    - theme
before_install:
  #  配置git
  - git config --global user.name "Ahaochan"
  - git config --global user.email "844394093@qq.com"
  # 由于使用了yarn，所以需要下载，如不用yarn这两行可以删除
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  # npm模块安装
  - yarn global add hexo-cli
  # - yarn remove hexo-renderer-marked
  - yarn add hexo-renderer-kramed
  - yarn add hexo-asset-image
  - yarn add hexo-generator-searchdb
  - yarn add hexo-generator-feed
  - yarn add hexo-related-popular-posts
  - yarn add hexo-symbols-count-time
  - yarn add hexo-generator-sitemap
  - yarn add hexo-generator-baidu-sitemap
  - yarn add hexo-deployer-git
  - npm install hexo-leancloud-counter-security
  - yarn add hexo-helper-live2d
  - yarn add theme-next/next-util

  # next.yml配置文件解密
  - openssl aes-256-cbc -K $encrypted_3873d9e40d23_key -iv $encrypted_3873d9e40d23_iv -in source/_data/next.yml.enc -out source/_data/next.yml -d
  # 将 GitHub Token 替换到 next.yml 中
  - sed -i "s/REPO_TOKEN/${REPO_TOKEN}/" source/_data/next.yml
  - sed -i "s/CODING_TOKEN/${CODING_TOKEN}/" source/_data/next.yml
  # next主题下载
  - git clone https://github.com/theme-next/hexo-theme-next themes/next
  - cd themes/next && git checkout v7.7.2 && cd -
  # next主题依赖下载
  - git clone https://github.com/theme-next/theme-next-pdf themes/next/source/lib/pdf
  #- git clone https://github.com/theme-next/theme-next-reading-progress themes/next/source/lib/reading_progress
  #- git clone https://github.com/theme-next/theme-next-fastclick themes/next/source/lib/fastclick
  #- git clone https://github.com/theme-next/theme-next-jquery-lazyload themes/next/source/lib/jquery_lazyload # https://github.com/theme-next/theme-next-lazyload
  - git clone https://github.com/theme-next/theme-next-pace themes/next/source/lib/pace
  #- git clone https://github.com/theme-next/theme-next-canvas-nest themes/next/source/lib/canvas-nest
  #- git clone https://github.com/theme-next/theme-next-fancybox3 themes/next/source/lib/fancybox
  # - git clone https://github.com/theme-next/theme-next-quicklink.git themes/next/source/lib/quicklink
install:
  # 不用yarn的话这里改成 npm i 即可
  - yarn
script:
  # 配置 LeanCloud
  - hexo lc-counter register $leancloud_username $leancloud_password --config source/_data/next.yml
  - hexo clean --config source/_data/next.yml
  - hexo g --config source/_data/next.yml
  - hexo d --config source/_data/next.yml
