# 使用语言
language: node_js
# node版本
node_js: stable
# 设置只监听哪个分支
branches:
  only:
  - source
# tarvis生命周期执行顺序详见官网文档
before_install:
- git config --global user.name "Ahaochan"
- git config --global user.email "844394093@qq.com"
- npm install -g hexo-cli
install:
- npm i
script:
- hexo clean
- hexo g
#- hexo clean --config source/_data/next.yml
#- hexo g --config source/_data/next.yml
after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
# 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的
- git remote add origin git@github.com:Ahaochan/Ahaochan.github.io.git
- git push --quiet --force https://$REPO_TOKEN@github.com/Ahaochan/Ahaochan.github.io.git master
