# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Hexo Blog CI

on:
  push:
    branches: [ source ]
    paths-ignore:
      - README.md

env:
  # Git用户信息
  GIT_USERNAME: Ahaochan
  GIT_EMAIL: 844394093@qq.com
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  # 主题仓库
  THEME_REPO: next-theme/hexo-theme-next
  THEME_VERSION: v8.8.2
  THEME_PATH: themes/next
  # 主题配置
  CONFIG_REPO: ${{ secrets.CONFIG_REPO }}
  CONFIG_NAME: _config.next.yml
  LEANCLOUD_USERNAME: ${{ secrets.LEANCLOUD_USERNAME }}
  LEANCLOUD_PASSWORD: ${{ secrets.LEANCLOUD_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: source
      - name: Checkout theme repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.THEME_REPO }}
          ref: ${{ env.THEME_VERSION }}
          path: ${{ env.THEME_PATH }}
      - name: Node.js ${{ matrix.node-version }} Use
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Node.js modules Cache
        uses: actions/cache@v2
        with:
          # path: node_modules # https://github.com/actions/cache/blob/9ab95382c899bf0953a0c6c1374373fc40456ffe/examples.md#node---npm
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Git Config
        run: |
          git config --global user.name "${{ env.GIT_USERNAME }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"
          git clone ${{ env.CONFIG_REPO }} config
          cp config/${{ env.CONFIG_NAME }} ${{ env.CONFIG_NAME }}
          sed -i "s/REPO_TOKEN/${{ env.REPO_TOKEN }}/" _config.yml
          git clone https://github.com/theme-next/theme-next-pdf themes/next/source/lib/pdf
          git clone https://github.com/theme-next/theme-next-pace themes/next/source/lib/pace
      - name: Hexo Install dependencies
        run: |
          yarn global add hexo-cli
          yarn add hexo-generator-searchdb
          yarn add hexo-generator-sitemap
          yarn add hexo-generator-baidu-sitemap
          yarn add hexo-deployer-git
          yarn add hexo-helper-live2d
          yarn add theme-next/next-util
          yarn
      - name: Hexo deploy
        run: |
          yarn run hexo clean
          yarn run hexo g
          yarn run hexo d
